sonar.projectKey=anime-api
sonar.projectName=Anime API
sonar.sources=.
sonar.exclusions=node_modules/**,package-lock.json
sonar.host.url=http://localhost:9000
sonar.token=sqa_243aa4d02eac1f4187ef344651c5d1b9f0d08d1a

